"""create finance long format tables

Revision ID: 39a3df335f9e
Revises: 
Create Date: 2026-05-24 11:57:44.595412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a3df335f9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheet',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'metric', 'report_date', 'frequency'),
    schema='finance'
    )
    op.create_table('cash_flow',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'metric', 'report_date', 'frequency'),
    schema='finance'
    )
    op.create_table('financials',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'metric', 'report_date', 'frequency'),
    schema='finance'
    )
    op.create_table('income_stmt',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'metric', 'report_date', 'frequency'),
    schema='finance'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_stmt', schema='finance')
    op.drop_table('financials', schema='finance')
    op.drop_table('cash_flow', schema='finance')
    op.drop_table('balance_sheet', schema='finance')
    # ### end Alembic commands ###
