from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Date,
    Float,
    MetaData,
    PrimaryKeyConstraint,
    String,
    func,
)
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base(metadata=MetaData(schema="stocks"))


class ValidTicker(Base):
    __tablename__ = "valid_tickers"
    __table_args__ = {"schema": "stocks"}

    ticker = Column(String, primary_key=True, nullable=False)
    date = Column("date", Date, nullable=False, default="now()")
    currency_code = Column(String)
    market_cap = Column(BigInteger)
    total_revenue = Column(BigInteger)
    free_cash_flow = Column(BigInteger)
    total_assets = Column(BigInteger)
    validity = Column(Boolean, nullable=False)
    balance_sheet_annual_available = Column(Boolean, default=True)
    cashflow_annual_available = Column(Boolean, default=True)
    income_stmt_annual_available = Column(Boolean, default=True)
    financials_annual_available = Column(Boolean, default=True)
    balance_sheet_quarterly_available = Column(Boolean, default=True)
    cashflow_quarterly_available = Column(Boolean, default=True)
    income_stmt_quarterly_available = Column(Boolean, default=True)
    financials_quarterly_available = Column(Boolean, default=True)


class TickersList(Base):
    __tablename__ = "tickers_list"
    __table_args__ = (PrimaryKeyConstraint("ticker"), {"schema": "stocks"})

    ticker = Column(String, nullable=False)
    name = Column(String)
    exchange = Column(String)
    category_name = Column(String)
    country = Column(String)


class IncomeStatement(Base):
    __tablename__ = "income_stmt"
    __table_args__ = (
        PrimaryKeyConstraint("ticker", "report_date", "frequency"),
        {"schema": "stocks"},
    )

    ticker = Column(String, primary_key=True, nullable=False)
    insert_date = Column(Date, nullable=False, default="now()")
    report_date = Column(Date, primary_key=True, nullable=False)
    currency_code = Column(String)
    frequency = Column(String(10), primary_key=True, nullable=False)
    tax_effect_of_unusual_items = Column(Float)
    tax_rate_for_calcs = Column(Float)
    normalized_ebitda = Column(Float)
    net_income_from_continuing_operation_net_minority_interest = Column(Float)
    reconciled_depreciation = Column(Float)
    reconciled_cost_of_revenue = Column(Float)
    ebit = Column(Float)
    net_interest_income = Column(Float)
    interest_expense = Column(Float)
    interest_income = Column(Float)
    normalized_income = Column(Float)
    net_income_from_continuing_and_discontinued_operation = Column(Float)
    total_expenses = Column(Float)
    total_operating_income_as_reported = Column(Float)
    diluted_ni_availto_com_stockholders = Column(Float)
    net_income_common_stockholders = Column(Float)
    net_income = Column(Float)
    net_income_including_noncontrolling_interests = Column(Float)
    net_income_continuous_operations = Column(Float)
    tax_provision = Column(Float)
    pretax_income = Column(Float)
    other_income_expense = Column(Float)
    other_non_operating_income_expenses = Column(Float)
    net_non_operating_interest_income_expense = Column(Float)
    interest_expense_non_operating = Column(Float)
    interest_income_non_operating = Column(Float)
    operating_income = Column(Float)
    operating_expense = Column(Float)
    research_and_development = Column(Float)
    selling_general_and_administration = Column(Float)
    gross_profit = Column(Float)
    cost_of_revenue = Column(Float)
    total_revenue = Column(Float)
    operating_revenue = Column(Float)
    diluted_average_shares = Column(Float)
    basic_average_shares = Column(Float)
    total_unusual_items = Column(Float)
    total_unusual_items_excluding_goodwill = Column(Float)
    diluted_eps = Column(Float)
    basic_eps = Column(Float)
    minority_interests = Column(Float)
    special_income_charges = Column(Float)
    gain_on_sale_of_ppe = Column(Float)
    restructuring_and_merger_and_acquisition = Column(Float)
    earnings_from_equity_interest = Column(Float)
    gain_on_sale_of_security = Column(Float)
    other_operating_expenses = Column(Float)
    restructuring_and_mergern_acquisition = Column(Float)
    average_dilution_earnings = Column(Float)
    preferred_stock_dividends = Column(Float)
    net_income_discontinuous_operations = Column(Float)
    impairment_of_capital_assets = Column(Float)
    depreciation_amortization_depletion_income_statement = Column(Float)
    depreciation_and_amortization_in_income_statement = Column(Float)
    otherunder_preferred_stock_dividend = Column(Float)
    selling_and_marketing_expense = Column(Float)
    general_and_administrative_expense = Column(Float)
    other_special_charges = Column(Float)
    write_off = Column(Float)
    total_other_finance_cost = Column(Float)
    amortization = Column(Float)
    amortization_of_intangibles_income_statement = Column(Float)
    other_gand_a = Column(Float)
    salaries_and_wages = Column(Float)
    excise_taxes = Column(Float)


class Financials(Base):
    __tablename__ = "financials"
    __table_args__ = (
        PrimaryKeyConstraint("ticker", "report_date", "frequency"),
        {"schema": "stocks"},
    )

    ticker = Column(String, primary_key=True, nullable=False)
    insert_date = Column(Date, nullable=False, default="now()")
    report_date = Column(Date, primary_key=True, nullable=False)
    currency_code = Column(String)
    frequency = Column(String(10), primary_key=True, nullable=False)
    tax_effect_of_unusual_items = Column(Float)
    tax_rate_for_calcs = Column(Float)
    normalized_ebitda = Column(Float)
    net_income_from_continuing_operation_net_minority_interest = Column(Float)
    reconciled_depreciation = Column(Float)
    reconciled_cost_of_revenue = Column(Float)
    ebitda = Column(Float)
    ebit = Column(Float)
    net_interest_income = Column(Float)
    interest_expense = Column(Float)
    interest_income = Column(Float)
    normalized_income = Column(Float)
    net_income_from_continuing_and_discontinued_operation = Column(Float)
    total_expenses = Column(Float)
    total_operating_income_as_reported = Column(Float)
    diluted_average_shares = Column(Float)
    basic_average_shares = Column(Float)
    diluted_eps = Column(Float)
    basic_eps = Column(Float)
    diluted_ni_availto_com_stockholders = Column(Float)
    net_income_common_stockholders = Column(Float)
    net_income = Column(Float)
    net_income_including_noncontrolling_interests = Column(Float)
    net_income_continuous_operations = Column(Float)
    tax_provision = Column(Float)
    pretax_income = Column(Float)
    other_income_expense = Column(Float)
    other_non_operating_income_expenses = Column(Float)
    net_non_operating_interest_income_expense = Column(Float)
    interest_expense_non_operating = Column(Float)
    interest_income_non_operating = Column(Float)
    operating_income = Column(Float)
    operating_expense = Column(Float)
    research_and_development = Column(Float)
    selling_general_and_administration = Column(Float)
    gross_profit = Column(Float)
    cost_of_revenue = Column(Float)
    total_revenue = Column(Float)
    operating_revenue = Column(Float)
    total_unusual_items = Column(Float)
    total_unusual_items_excluding_goodwill = Column(Float)
    average_dilution_earnings = Column(Float)
    preferred_stock_dividends = Column(Float)
    minority_interests = Column(Float)
    net_income_discontinuous_operations = Column(Float)
    special_income_charges = Column(Float)
    gain_on_sale_of_ppe = Column(Float)
    write_off = Column(Float)
    impairment_of_capital_assets = Column(Float)
    earnings_from_equity_interest = Column(Float)
    depreciation_amortization_depletion_income_statement = Column(Float)
    depreciation_and_amortization_in_income_statement = Column(Float)
    otherunder_preferred_stock_dividend = Column(Float)
    other_special_charges = Column(Float)
    restructuring_and_mergern_acquisition = Column(Float)
    general_and_administrative_expense = Column(Float)
    other_gand_a = Column(Float)
    salaries_and_wages = Column(Float)


class Cashflow(Base):
    __tablename__ = "cashflow"
    __table_args__ = (
        PrimaryKeyConstraint("ticker", "report_date", "frequency"),
        {"schema": "stocks"},
    )

    ticker = Column(String(100), nullable=False)
    insert_date = Column(Date, nullable=False, default=func.now())
    report_date = Column(Date, nullable=False)
    currency_code = Column(String(10))
    frequency = Column(String(10), nullable=False)
    free_cash_flow = Column(Float)
    repurchase_of_capital_stock = Column(Float)
    repayment_of_debt = Column(Float)
    issuance_of_debt = Column(Float)
    issuance_of_capital_stock = Column(Float)
    capital_expenditure = Column(Float)
    interest_paid_supplemental_data = Column(Float)
    income_tax_paid_supplemental_data = Column(Float)
    end_cash_position = Column(Float)
    beginning_cash_position = Column(Float)
    changes_in_cash = Column(Float)
    financing_cash_flow = Column(Float)
    cash_flow_from_continuing_financing_activities = Column(Float)
    net_other_financing_charges = Column(Float)
    cash_dividends_paid = Column(Float)
    common_stock_dividend_paid = Column(Float)
    net_common_stock_issuance = Column(Float)
    common_stock_payments = Column(Float)
    common_stock_issuance = Column(Float)
    net_issuance_payments_of_debt = Column(Float)
    net_short_term_debt_issuance = Column(Float)
    short_term_debt_payments = Column(Float)
    short_term_debt_issuance = Column(Float)
    net_long_term_debt_issuance = Column(Float)
    long_term_debt_payments = Column(Float)
    long_term_debt_issuance = Column(Float)
    investing_cash_flow = Column(Float)
    cash_flow_from_continuing_investing_activities = Column(Float)
    net_other_investing_changes = Column(Float)
    net_investment_purchase_and_sale = Column(Float)
    sale_of_investment = Column(Float)
    purchase_of_investment = Column(Float)
    net_business_purchase_and_sale = Column(Float)
    purchase_of_business = Column(Float)
    net_ppe_purchase_and_sale = Column(Float)
    purchase_of_ppe = Column(Float)
    operating_cash_flow = Column(Float)
    cash_flow_from_continuing_operating_activities = Column(Float)
    change_in_working_capital = Column(Float)
    change_in_other_working_capital = Column(Float)
    change_in_other_current_liabilities = Column(Float)
    change_in_other_current_assets = Column(Float)
    change_in_payables_and_accrued_expense = Column(Float)
    change_in_payable = Column(Float)
    change_in_account_payable = Column(Float)
    change_in_inventory = Column(Float)
    change_in_receivables = Column(Float)
    changes_in_account_receivables = Column(Float)
    other_non_cash_items = Column(Float)
    stock_based_compensation = Column(Float)
    deferred_tax = Column(Float)
    deferred_income_tax = Column(Float)
    depreciation_amortization_depletion = Column(Float)
    depreciation_and_amortization = Column(Float)
    net_income_from_continuing_operations = Column(Float)
    cash_from_discontinued_financing_activities = Column(Float)
    dividends_received_cfi = Column(Float)
    sale_of_business = Column(Float)
    capital_expenditure_reported = Column(Float)
    cash_from_discontinued_operating_activities = Column(Float)
    provisionand_write_offof_assets = Column(Float)
    asset_impairment_charge = Column(Float)
    operating_gains_losses = Column(Float)
    pension_and_employee_benefit_expense = Column(Float)
    gain_loss_on_investment_securities = Column(Float)
    effect_of_exchange_rate_changes = Column(Float)
    change_in_accrued_expense = Column(Float)
    change_in_tax_payable = Column(Float)
    change_in_income_tax_payable = Column(Float)
    amortization_cash_flow = Column(Float)
    amortization_of_intangibles = Column(Float)
    depreciation = Column(Float)


class BalanceSheet(Base):
    __tablename__ = "balance_sheet"
    __table_args__ = (
        PrimaryKeyConstraint("ticker", "report_date", "frequency"),
        {"schema": "stocks"},
    )

    ticker = Column(String(100), nullable=False)
    insert_date = Column(Date, nullable=False, default=func.now())
    report_date = Column(Date, nullable=False)
    currency_code = Column(String(10))
    frequency = Column(String(10), nullable=False)
    Ordinary_Shares_Number = Column(Float)
    Share_Issued = Column(Float)
    Net_Debt = Column(Float)
    Total_Debt = Column(Float)
    Tangible_Book_Value = Column(Float)
    Invested_Capital = Column(Float)
    Working_Capital = Column(Float)
    Net_Tangible_Assets = Column(Float)
    Common_Stock_Equity = Column(Float)
    Total_Capitalization = Column(Float)
    Total_Equity_Gross_Minority_Interest = Column(Float)
    Stockholders_Equity = Column(Float)
    Gains_Losses_Not_Affecting_Retained_Earnings = Column(Float)
    Retained_Earnings = Column(Float)
    Capital_Stock = Column(Float)
    Common_Stock = Column(Float)
    Total_Liabilities_Net_Minority_Interest = Column(Float)
    Total_Non_Current_Liabilities_Net_Minority_Interest = Column(Float)
    Other_Non_Current_Liabilities = Column(Float)
    Tradeand_Other_Payables_Non_Current = Column(Float)
    Long_Term_Debt_And_Capital_Lease_Obligation = Column(Float)
    Long_Term_Debt = Column(Float)
    Current_Liabilities = Column(Float)
    Other_Current_Liabilities = Column(Float)
    Current_Deferred_Liabilities = Column(Float)
    Current_Deferred_Revenue = Column(Float)
    Current_Debt_And_Capital_Lease_Obligation = Column(Float)
    Current_Debt = Column(Float)
    Other_Current_Borrowings = Column(Float)
    Commercial_Paper = Column(Float)
    Payables_And_Accrued_Expenses = Column(Float)
    Payables = Column(Float)
    Accounts_Payable = Column(Float)
    Total_Assets = Column(Float)
    Total_Non_Current_Assets = Column(Float)
    Other_Non_Current_Assets = Column(Float)
    Investments_And_Advances = Column(Float)
    Other_Investments = Column(Float)
    Investmentin_Financial_Assets = Column(Float)
    Available_For_Sale_Securities = Column(Float)
    Net_PPE = Column(Float)
    Accumulated_Depreciation = Column(Float)
    Gross_PPE = Column(Float)
    Leases = Column(Float)
    Machinery_Furniture_Equipment = Column(Float)
    Land_And_Improvements = Column(Float)
    Properties = Column(Float)
    Current_Assets = Column(Float)
    Other_Current_Assets = Column(Float)
    Inventory = Column(Float)
    Receivables = Column(Float)
    Other_Receivables = Column(Float)
    Accounts_Receivable = Column(Float)
    Cash_Cash_Equivalents_And_Short_Term_Investments = Column(Float)
    Other_Short_Term_Investments = Column(Float)
    Cash_And_Cash_Equivalents = Column(Float)
    Cash_Equivalents = Column(Float)
    Cash_Financial = Column(Float)
